#!/bin/bash
# Railway Dashboard Setup Helper
# Generuje komendy i instrukcje dla Railway Dashboard

set -euo pipefail

# Configuration
PROJECT_NAME="${PROJECT_NAME:-WIG}"
REPO="${REPO:-SynergiaOS/trading_wig}"

# Logging functions
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     🚀 RAILWAY DASHBOARD SETUP HELPER                         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Ten skrypt generuje wszystkie komendy i instrukcje potrzebne"
echo "do konfiguracji projektu $PROJECT_NAME w Railway Dashboard."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

log "📋 PROJEKT: $PROJECT_NAME"
log "📦 REPO: $REPO"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ============================================================================
# KROK 1: Utworzenie projektu
# ============================================================================
log "🔹 KROK 1: UTWORZENIE PROJEKTU"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Otwórz Railway Dashboard:"
echo "   https://railway.app"
echo ""
echo "2. Kliknij 'New Project'"
echo ""
echo "3. Nazwa projektu: $PROJECT_NAME"
echo ""
echo "4. Environment: production (domyślny)"
echo ""
read -p "Naciśnij Enter gdy projekt będzie utworzony..."

# ============================================================================
# KROK 2: Frontend Service
# ============================================================================
echo ""
log "🔹 KROK 2: FRONTEND SERVICE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. W projekcie kliknij '+ New Service'"
echo "2. Wybierz 'GitHub Repo' → $REPO"
echo "3. Nazwa serwisu: frontend"
echo ""
echo "4. Settings → Build:"
echo "   Dockerfile Path: Dockerfile.frontend"
echo ""
echo "5. Settings → Deploy:"
echo "   Health Check Path: /"
echo "   Health Check Timeout: 100"
echo "   Restart Policy: ON_FAILURE"
echo "   Max Retries: 10"
echo ""
echo "6. Settings → Networking:"
echo "   Kliknij 'Generate Domain'"
echo ""
echo "7. Settings → Variables (dodaj):"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ NODE_ENV=production                     │"
echo "   │ PORT=4173                               │"
echo "   │ VITE_REFRESH_INTERVAL=30000             │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   ⚠️  UWAGA: VITE_API_URL i VITE_ANALYSIS_API_URL"
echo "              dodasz po deploy Backend i Analysis"
echo ""
read -p "Naciśnij Enter gdy Frontend będzie skonfigurowany..."

# ============================================================================
# KROK 3: Backend Service
# ============================================================================
echo ""
log "🔹 KROK 3: BACKEND SERVICE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Kliknij '+ New Service'"
echo "2. Wybierz 'GitHub Repo' → $REPO"
echo "3. Nazwa serwisu: backend"
echo ""
echo "4. Settings → Build:"
echo "   Dockerfile Path: Dockerfile.backend"
echo ""
echo "5. Settings → Deploy:"
echo "   Health Check Path: /data"
echo "   Health Check Timeout: 100"
echo ""
echo "6. Settings → Networking:"
echo "   Kliknij 'Generate Domain'"
echo "   📝 SKOPIUJ URL: https://backend-production-XXXX.up.railway.app"
echo ""
echo "7. Settings → Variables (dodaj):"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ PORT=8000                               │"
echo "   │ HOST=0.0.0.0                            │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   📝 Opcjonalnie (jeśli masz osobne serwisy dla baz danych):"
echo "   ┌────────────────────────────────────────────────────────────┐"
echo "   │ POCKETBASE_URL=http://pocketbase.railway.internal:8090    │"
echo "   │ QUESTDB_HOST=questdb.railway.internal                     │"
echo "   │ QUESTDB_PORT=9009                                          │"
echo "   │ QUESTDB_USER=admin                                         │"
echo "   │ QUESTDB_PASSWORD=quest                                     │"
echo "   │ REDIS_URL=redis://redis.railway.internal:6379             │"
echo "   └────────────────────────────────────────────────────────────┘"
echo ""
read -p "Podaj Backend URL (skopiuj z Railway): " BACKEND_URL
BACKEND_URL=${BACKEND_URL:-https://backend-production.up.railway.app}
echo "✅ Backend URL: $BACKEND_URL"
echo ""
read -p "Naciśnij Enter gdy Backend będzie skonfigurowany..."

# ============================================================================
# KROK 4: Analysis Service
# ============================================================================
echo ""
log "🔹 KROK 4: ANALYSIS SERVICE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Kliknij '+ New Service'"
echo "2. Wybierz 'GitHub Repo' → $REPO"
echo "3. Nazwa serwisu: analysis"
echo ""
echo "4. Settings → Build:"
echo "   Dockerfile Path: Dockerfile.analysis"
echo ""
echo "5. Settings → Deploy:"
echo "   Health Check Path: /api/analysis"
echo "   Health Check Timeout: 100"
echo ""
echo "6. Settings → Networking:"
echo "   Kliknij 'Generate Domain'"
echo "   📝 SKOPIUJ URL: https://analysis-production-XXXX.up.railway.app"
echo ""
echo "7. Settings → Variables (dodaj):"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ ANALYSIS_PORT=8001                      │"
echo "   │ ANALYSIS_HOST=0.0.0.0                   │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   📝 Opcjonalnie (te same co Backend):"
echo "   POCKETBASE_URL, QUESTDB_HOST, QUESTDB_PORT, etc."
echo ""
read -p "Podaj Analysis URL (skopiuj z Railway): " ANALYSIS_URL
ANALYSIS_URL=${ANALYSIS_URL:-https://analysis-production.up.railway.app}
echo "✅ Analysis URL: $ANALYSIS_URL"
echo ""
read -p "Naciśnij Enter gdy Analysis będzie skonfigurowany..."

# ============================================================================
# KROK 5: Zaktualizuj Frontend Variables
# ============================================================================
echo ""
log "🔹 KROK 5: ZAKTUALIZUJ FRONTEND VARIABLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Wróć do Frontend Service"
echo "2. Settings → Variables → Add Variable"
echo "3. Dodaj następujące zmienne:"
echo ""
echo "   ┌─────────────────────────────────────────────────────────────┐"
echo "   │ VITE_API_URL=$BACKEND_URL"
echo "   │ VITE_ANALYSIS_API_URL=$ANALYSIS_URL"
echo "   └─────────────────────────────────────────────────────────────┘"
echo ""
echo "4. Railway automatycznie redeploy Frontend po zmianie zmiennych"
echo ""
read -p "Naciśnij Enter gdy Frontend variables będą zaktualizowane..."

# ============================================================================
# PODSUMOWANIE
# ============================================================================
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     ✅ KONFIGURACJA ZAKOŃCZONA!                               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 PODSUMOWANIE:"
echo ""
echo "✅ Projekt: $PROJECT_NAME"
echo "✅ Frontend URL: (sprawdź w Railway Dashboard)"
echo "✅ Backend URL: $BACKEND_URL"
echo "✅ Analysis URL: $ANALYSIS_URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 WERYFIKACJA:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Sprawdź czy wszystkie serwisy działają:"
echo ""
echo "# Frontend"
echo "curl https://frontend-production-XXXX.up.railway.app"
echo ""
echo "# Backend"
echo "curl $BACKEND_URL/data"
echo ""
echo "# Analysis"
echo "curl $ANALYSIS_URL/api/analysis"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOKUMENTACJA:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  📘 RAILWAY_COMPLETE_GUIDE.md - Kompletny przewodnik"
echo "  📙 RAILWAY_ENV_SETUP.md - Zmienne środowiskowe"
echo "  📗 RAILWAY_FIX_AUTH.md - Naprawa autentykacji"
echo ""

